services:
  backend-da:
    build:
      context: ./backend-da
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: unless-stopped

  backend-llm:
    build:
      context: ./backend-llm
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    restart: unless-stopped

  frontend-ui:
    build:
      context: ./frontend-ui
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - backend-da
      - backend-llm

networks:
  default:
    driver: bridge
