from pydantic import BaseModel, Field, field_validator
from enum import Enum
from datetime import datetime, timezone
from typing import Optional, List, Any
import uuid


class ModelProvider(str, Enum):
    OPENAI = "openai"
    GOOGLE = "google"
    GROQ = "groq"


# Helper model for chat history input in the API
class ChatMessageAPI(BaseModel):
    role: str = Field(..., examples=["user", "assistant"])
    content: str

    @field_validator('role')
    @classmethod
    def role_must_be_valid(cls, v: str) -> str:
        role_lower = v.lower()
        if role_lower not in ["user", "assistant", "system", "human", "ai"]:
            raise ValueError(
                "Role must be one of 'user', 'assistant', 'system', 'human', 'ai'")
        return role_lower


class SingleModelChatRequest(BaseModel):
    """Request body for individual LLM chat endpoints."""
    question: str = Field(..., examples=["What is the capital of France?"])
    session_id: Optional[str] = Field(
        default_factory=lambda: str(uuid.uuid4()))
    chat_history: Optional[List[ChatMessageAPI]] = Field(
        default_factory=list,
        examples=[[{"role": "user", "content": "My name is Bob."}]]
    )
    system_prompts: Optional[List[str]] = Field(
        default_factory=list,
        description="List of system prompts to prepend to the chat history for context"
    )

    @field_validator('session_id', mode='before')
    @classmethod
    def set_session_id_if_none(cls, v: Optional[str]) -> str:
        return v or str(uuid.uuid4())


class QueryResponse(BaseModel):
    """
    Represents a single response returned by an AI model.

    Attributes:
        answer (str): The textual response generated by the AI model.
        session_id (str): Unique identifier for the session this response belongs to.
        model (str): The specific model name that generated the response (e.g., "gpt-5", "gemini-2.5-flash").
        provider (ModelProvider): The provider associated with the model (e.g., OpenAI, Google, Groq).
        request_timestamp (datetime): The timestamp when the query was sent to the model.
        response_timestamp (datetime): The timestamp when the response was received from the model.
        latency_ms (float): The total time taken to receive the model's response, in milliseconds.
        usage (Optional[Any]): Token usage information from the LLM provider (format varies by provider).
    """
    answer: Optional[str] = None
    raw_response: Optional[Any] = None
    error_message: Optional[str] = None
    session_id: str
    model: str  # Changed from ModelName enum to string for dynamic models
    provider: ModelProvider
    request_timestamp: datetime
    response_timestamp: datetime
    latency_ms: float
    usage: Optional[Any] = None

    @field_validator('request_timestamp', 'response_timestamp', mode='before')
    @classmethod
    def ensure_datetime_is_aware(cls, v: datetime) -> datetime:
        """Validates that the datetime field is timezone-aware."""
        if v.tzinfo is None:
            raise ValueError("Datetime must be timezone-aware (UTC).")
        return v.astimezone(timezone.utc)


class ComparisonResponse(BaseModel):
    """
    Represents the collection of responses from multiple language models for a single input query.

    Attributes:
        original_question (str): The user-provided question that was submitted to all models.
        session_id (str): Unique identifier used to group all model responses under a single session.
        responses (List[QueryResponse]): A list of individual responses from each model involved in the comparison.
        comparison_timestamp (datetime): The timestamp when the comparison was completed.
    """
    original_question: str
    session_id: str
    responses: List[QueryResponse]
    comparison_timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc))


class ModelInfo(BaseModel):
    """Model information returned by discovery service."""
    id: str
    name: str
    provider: str
    description: Optional[str] = None


class AvailableModelsResponse(BaseModel):
    """Response containing all available models grouped by provider."""
    openai: List[ModelInfo]
    google: List[ModelInfo]
    groq: List[ModelInfo]
